apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
    - host: "main.durgasri.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: spec-service
                port:
                  number: 9000
