name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of Docker Image'
        required: true

env:
  IMAGE_NAME: app

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]

    steps:

    - name: get arch
      run: |
        uname -a
        cat /etc/*release

    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }} --platform linux/${{ matrix.arch }} -f Dockerfile .

    - name: Tag the Docker image with 'latest'
      run: docker tag docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }}  docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push the Docker image with version tag
      run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }}

    - name: Push the Docker image with 'latest' tag
      run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
